version: '3.1'
services:
  taroco-registry:
    build:
      context: ./
      dockerfile: Dockerfile-registry
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /data/logs/taroco/:/logs/

  taroco-config:
    links:
      - taroco-registry:taroco-registry
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always
    environment:
      - EUREKA_SERVER_HOST=taroco-registry
    depends_on:
      - taroco-registry
    volumes:
      - /data/logs/taroco/:/logs/

  taroco-authentication-server:
    links:
      - taroco-registry:taroco-registry
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    depends_on:
      - taroco-config
    volumes:
      - /data/logs/taroco/:/logs/

  taroco-upms:
    links:
      - taroco-registry:taroco-registry
    build:
      context: ./
      dockerfile: Dockerfile-upms
    restart: always
    depends_on:
      - taroco-config
    volumes:
      - /data/logs/taroco/:/logs/

  taroco-gateway:
    links:
      - taroco-registry:taroco-registry
      - taroco-authentication-server:taroco-authentication-server
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    depends_on:
      - taroco-config
      - taroco-authentication-server
    volumes:
      - /data/logs/taroco/:/logs/
