version: '2'
services:
  taroco-authentication-server:
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    volumes:
      - /data/logs/taroco-authentication-server/:/logs/taroco-authentication-server/
    networks:
      - taroco

  taroco-upms:
    build:
      context: ./
      dockerfile: Dockerfile-upms
    restart: always
    volumes:
      - /data/logs/taroco-upms-service/:/logs/taroco-upms-service/
    networks:
      - taroco

  taroco-gateway:
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    depends_on:
      - taroco-authentication-server
    volumes:
      - /data/logs/taroco-gateway/:/logs/taroco-gateway/
    networks:
      - taroco

networks:
  taroco:
