version: '2'
services:

  taroco-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: taroco@1234
      MYSQL_DATABASE: taroco-oauth2
    networks:
      taroco:
        aliases:
          - taroco-mysql

  taroco-redis:
    build:
      context: ./
      dockerfile: Dockerfile-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data
    networks:
      taroco:
        aliases:
          - taroco-redis
networks:
  taroco:
