version: '3.1'
volumes:
  - /data/logs/taroco/:/logs/
services:
  taroco-registry:
    build:
      context: ./
      dockerfile: Dockerfile-registry
    restart: always
    ports:
      - 9000:9000

  taroco-config:
    links:
      - taroco-registry:taroco-registry
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always
    environment:
      - EUREKA_SERVER_HOST=taroco-registry
    depends_on:
      - taroco-registry

  taroco-authentication-server:
    links:
      - taroco-config:taroco-config
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    depends_on:
      - taroco-config

  taroco-upms:
    links:
      - taroco-config:taroco-config
    build:
      context: ./
      dockerfile: Dockerfile-upms
    restart: always
    depends_on:
      - taroco-config

  taroco-gateway:
    links:
      - taroco-config:taroco-config
      - taroco-authentication-server:taroco-authentication-server
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    depends_on:
      - taroco-config
