version: '3.1'
services:
  taroco-authentication-server:
    external_links:
      - taroco-registry
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    volumes:
      - /data/logs/taroco/:/logs/taroco-authentication-server/

  taroco-upms:
    external_links:
      - taroco-registry
    build:
      context: ./
      dockerfile: Dockerfile-upms
    restart: always
    volumes:
      - /data/logs/taroco/:/logs/taroco-upms-service/

  taroco-gateway:
    external_links:
      - taroco-registry
    links:
      - taroco-authentication-server
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    depends_on:
      - taroco-authentication-server
    volumes:
      - /data/logs/taroco/:/logs/taroco-gateway/
