# 服务网关配置

# 路由配置
zuul:
  retryable: true
  #　忽略所有默认路由
  ignored-services: '*'
  rate-limit:
    # 微服务实例限流指标 1000/s
    permits-per-second: 1000
  routes:
    taroco-admin: # 服务治理
      path: /taroco-admin/**
      serviceId: taroco-admin
    taroco-registry: # 注册中心
      path: /taroco-registry/**
      serviceId: taroco-registry
    taroco-monitor: # 服务监控
      path: /taroco-monitor/**
      serviceId: taroco-monitor
    admin: # 权限管理服务
      path: /admin/**
      serviceId: taroco-upms-service
    auth: # 统一认证服务
      path: /auth/**
      serviceId: taroco-authentication-server

security:
  encode:
    key: '1234567887654321' #必须16位
  validate:
    code: false
    preview: true
  sessions: stateless
  oauth2:
    client:
      client-id: taroco
      client-secret: taroco
    resource:
      jwt:
         key-uri: ${base.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

ignore:
  urls:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/menu/userMenu
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
  clients:
    - app
