# 注册中心配置

# 在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
eureka:
  client:
    # 表示是否注册自身到eureka服务器
    register-with-eureka: true
    #是否从eureka服务器获取注册信息
    fetch-registry: false
  server:
    # 关闭自我保护模式(生产环境不建议关闭)
    enable-self-preservation: false
    # 清理无效节点间隔（单位毫秒，默认是60*1000）开发阶段调小
    eviction-interval-timer-in-ms: 5000